build:
  image: library/golang:1.5
  commands:
    - go version
    - go get github.com/kardianos/govendor
    - go get github.com/go-playground/overalls
    - go get github.com/mattn/goveralls
    - go get bitbucket.org/liamstask/goose/cmd/goose
    - govendor sync
    - go vet ./...
    - createdb zqz-test
    - goose -env test up
    - goose -env test status
    - go test ./... -race
    - overalls -project=github.com/zqzca/back -covermode=count
    - goveralls -coverprofile=overalls.coverprofile -repotoken ${COVERALLS_TOKEN}
